name: Java Jar

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      LANG: en_US.UTF-8

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [17]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        # java: [8, 11, 17, 21]

    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Checkout Core
        uses: actions/checkout@v3
        with:
          repository: 'MarcelloPerathoner/josm'
          path: 'core'
          fetch-depth: 256

      - name: Checkout Plugins
        uses: actions/checkout@v3
        with:
          path: 'plugins'
          fetch-depth: 256

      - name: Build Core
        run: |
          cd core
          ./gradlew jar
          cd ..

      - name: Build Plugins
        run: |
          cd plugins
          ant dist
          cd ..

      - name: Generate release tag
        id: tag
        run: |
          echo "RELEASE_TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Generate MANIFEST
        id: manifest
        run: |
          00_scripts/manifest.py --icons --root-dir plugins/build/libs *.jar > plugins/build/libs/MANIFEST

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: |
            plugins/build/libs/*.jar
            plugins/build/libs/MANIFEST
