name: Java Jar

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      LANG: en_US.UTF-8
      JOSM_DIR: core

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [17]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        # java: [8, 11, 17, 18, 19]

    steps:
      - name: Checkout Plugins
        uses: actions/checkout@v3
        with:
          fetch-depth: 256

      - name: Checkout Core
        uses: actions/checkout@v3
        with:
          repository: 'MarcelloPerathoner/josm'
          path: 'core'
          fetch-depth: 256

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Build Core
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jar
          build-root-directory: core

      - name: Build Plugins
        run: |
          ant dist

      - name: Generate release tag
        id: tag
        run: |
          echo "RELEASE_TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: dist/*.jar
