name: Java Jar

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      LANG: en_US.UTF-8

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [17]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        # java: [8, 11, 17, 21]

    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Checkout Core
        run: |
          git clone --branch develop --depth=1 https://github.com/MarcelloPerathoner/josm.git core

      - name: Checkout Plugins
        run: |
          git clone --branch develop --depth=1 https://github.com/MarcelloPerathoner/josm-plugins.git plugins

      - name: Build Core
        run: |
          cd core
          ./gradlew jar
          echo "JOSM_DIR=$(pwd)" >> $GITHUB_ENV
          cd ..

      - name: Build Plugins
        run: |
          cd plugins
          ant dist
          cd ..

      - name: Generate release tag
        id: tag
        run: |
          echo "RELEASE_TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Generate MANIFEST
        id: manifest
        run: |
          cd plugins
          python 00_scripts/manifest.py --icons --root-dir build/libs *.jar > build/libs/MANIFEST
          cd ..

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: |
            plugins/build/libs/*.jar
            plugins/build/libs/MANIFEST
